### PR TITLE
Minor last minute revisions to 1.18 release notes

### PR DESCRIPTION
**Pull request by irydacea**
I'm in a rush so I can't write a full PR description here right now. Pls check the commit messages.

### CODE REVIEW

**Comment by irydacea** [comment]
Side note: I feel like we need to link to *something* explaining the EmmyLua thing (preferably in English).

**Comment by Pentarctagon** [comment]
Probably more useful would be documentation for setting it up so that UMC authors can use it?

**Review by Pentarctagon — APPROVED** [review]

**Comment by CelticMinstrel** [comment]
If it's about setting it up, I suppose the closest is this: https://luals.github.io/wiki/addons/

I think a little rework of the directory structure would be needed for those instructions to work though.

Also, based on that first link, apparently they're calling it "LuaCATS" now instead of "EmmyLua"…

**Comment by Pentarctagon** [comment]
> It does this through LuaCATS (Lua Comment And Type System) annotations, which are based off of EmmyLua annotations.

Reads to me like they're separate things, just that LuaCATS is a fork or something similar.

**Comment by CelticMinstrel** [comment]
Exactly, and the one we're using is the fork.

**Comment by Pentarctagon** [comment]
I'm going to go ahead and merge this as-is so everything is final for translators. If a good link to documentation for how to set this up is found, then I can add it manually to any po files since the contents of the `<a>` tag don't need any translation anyway.

**Pull request merged**
