### PR TITLE
Cs wip

### PR DESCRIPTION
**Pull request by MultiSeptim**

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Is this still WIP?

**Comment by MultiSeptim** [comment]
> Is this still WIP?

No, this is mistake by me. Please ignore it.

**Comment by Wedge009** [comment]
You can edit the title accordingly.

I know this isn't Wesnoth specifically, but should @hrubymar10 have a look over this first?

**Comment by irydacea** [comment]
Please make sure to squash when merging.

**Pull request closed without merging**
